<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="e5a38dd8240cd6d35a9c7f579fad8b95">
    <link href="25645ea212e3318008488f3283c1ae70" rel="stylesheet">
    <link rel="stylesheet" href="38a57924732567f1f34b4b8a7af5a2a4">
    <title>Document</title>
</head>

<body>
    <div id="particles-js">
        <header id="page-header">
            <div id="title-text-container">
                <h1 id="title-text">Cosmic Query</h1>
            </div>
            <div id="subtitle-text-container">
                <h2 id="subtitle-text">How much do you know about the universe?</h2>
            </div>
        </header>
    </div>

    <script src="60159d2603227ec66c50eefae285c2e0"></script>
    <script src="2db86728f9938e421d87b662e95958f1"></script>
</body>

</html>